// Initial Database Migration
// Command: Add-Migration InitialCreate
// Then: Update-Database

namespace pg_onion.Infrastructure.Migrations
{
    using Microsoft.EntityFrameworkCore.Migrations;

    /// <summary>
    /// To generate this migration, run:
    /// Add-Migration InitialCreate -Project pg_onion.Infrastructure -StartupProject pg_onion.Presentation
    /// 
    /// To apply the migration to database, run:
    /// Update-Database
    /// </summary>
    public partial class InitialCreate : Migration
    {
        // This is a template. The actual migration will be auto-generated by Entity Framework.
        // DO NOT edit this file directly - it will be overwritten.
        
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Migration code will be auto-generated
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Down migration will be auto-generated
        }
    }
}
